# Generated by Django 3.2.1 on 2021-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
