# Generated by Django 3.2.1 on 2021-05-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_review_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
    ]
